export const SING_UP = 'SIGN_UP'
export const SING_UP_SUCCESS = 'SING_UP_SUCCESS'
export const SING_UP_FAILED = 'SING_UP_FAILED'
export const SING_IN = 'SING_IN'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SING_IN_FAILED = 'SING_IN_FAILED'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_KITCHENS = 'FETCH_KITCHENS'
export const FETCH_KITCHENS_SUCCESS = 'FETCH_KITCHENS_SUCCESS'
export const FETCH_KITCHENS_FAILED = 'FETCH_KITCHENS_FAILED'

export const ADD_KITCHEN = 'ADD_KITCHEN'
export const ADD_KITCHEN_SUCCESS = 'ADD_KITCHEN_SUCCESS'
export const ADD_KITCHEN_FAILED = 'ADD_KITCHEN_FAILED'

export const EDIT_KITCHEN = 'EDIT_KITCHEN'
export const EDIT_KITCHEN_SUCCESS = 'EDIT_KITCHEN_SUCCESS'
export const EDIT_KITCHEN_FAILED = 'EDIT_KITCHEN_FAILED'

export const DELETE_KITCHEN = 'DELETE_KITCHEN'
export const DELETE_KITCHEN_SUCCESS = 'DELETE_KITCHEN_SUCCESS'
export const DELETE_KITCHEN_FAILED = 'DELETE_KITCHEN_FAILED'

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS'
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS'
export const FETCH_RESTAURANTS_FAILED = 'FETCH_RESTAURANTS_FAILED'

export const ADD_RESTAURANT = 'ADD_RESTAURANT'
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS'
export const ADD_RESTAURANT_FAILED = 'ADD_RESTAURANT_FAILED'

export const EDIT_RESTAURANT = 'EDIT_RESTAURANT'
export const EDIT_RESTAURANT_SUCCESS = 'EDIT_RESTAURANT_SUCCESS'
export const EDIT_RESTAURANT_FAILED = 'EDIT_RESTAURANT_FAILED'

export const DELETE_RESTAURANT = 'DELETE_RESTAURANT'
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS'
export const DELETE_RESTAURANT_FAILED = 'DELETE_RESTAURANT_FAILED'

export const FILTER_RESTAURANT = 'FILTER_RESTAURANT'
export const FILTER_RESTAURANT_SUCCESS = 'FILTER_RESTAURANT_SUCCESS'
export const FILTER_RESTAURANT_FAILED = 'FILTER_RESTAURANT_FAILED'

export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT'
export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS'
export const SEARCH_RESTAURANT_FAILED = 'SEARCH_RESTAURANT_FAILED'