export const SING_UP = 'SIGN_UP'
export const SING_UP_SUCCESS = 'SING_UP_SUCCESS'
export const SING_UP_FAILED = 'SING_UP_FAILED'
export const SING_IN = 'SING_IN'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SING_IN_FAILED = 'SING_IN_FAILED'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_KITCHENS = 'FETCH_KITCHENS'
export const FETCH_KITCHENS_SUCCESS = 'FETCH_KITCHENS_SUCCESS'
export const FETCH_KITCHENS_FAILED = 'FETCH_KITCHENS_FAILED'

export const ADD_KITCHEN = 'ADD_KITCHEN'
export const ADD_KITCHEN_SUCCESS = 'ADD_KITCHEN_SUCCESS'
export const ADD_KITCHEN_FAILED = 'ADD_KITCHEN_FAILED'

export const EDIT_KITCHEN = 'EDIT_KITCHEN'
export const EDIT_KITCHEN_SUCCESS = 'EDIT_KITCHEN_SUCCESS'
export const EDIT_KITCHEN_FAILED = 'EDIT_KITCHEN_FAILED'

export const DELETE_KITCHEN = 'DELETE_KITCHEN'
export const DELETE_KITCHEN_SUCCESS = 'DELETE_KITCHEN_SUCCESS'
export const DELETE_KITCHEN_FAILED = 'DELETE_KITCHEN_FAILED'

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS'
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS'
export const FETCH_RESTAURANTS_FAILED = 'FETCH_RESTAURANTS_FAILED'

export const GET_RESTAURANT = 'GET_RESTAURANT'
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS'
export const GET_RESTAURANT_FAILED = 'GET_RESTAURANT_FAILED'

export const ADD_RESTAURANT = 'ADD_RESTAURANT'
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS'
export const ADD_RESTAURANT_FAILED = 'ADD_RESTAURANT_FAILED'

export const EDIT_RESTAURANT = 'EDIT_RESTAURANT'
export const EDIT_RESTAURANT_SUCCESS = 'EDIT_RESTAURANT_SUCCESS'
export const EDIT_RESTAURANT_FAILED = 'EDIT_RESTAURANT_FAILED'

export const DELETE_RESTAURANT = 'DELETE_RESTAURANT'
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS'
export const DELETE_RESTAURANT_FAILED = 'DELETE_RESTAURANT_FAILED'

export const FILTER_RESTAURANT = 'FILTER_RESTAURANT'
export const FILTER_RESTAURANT_SUCCESS = 'FILTER_RESTAURANT_SUCCESS'
export const FILTER_RESTAURANT_FAILED = 'FILTER_RESTAURANT_FAILED'

export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT'
export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS'
export const SEARCH_RESTAURANT_FAILED = 'SEARCH_RESTAURANT_FAILED'

export const FETCH_ORDER = 'FETCH_ORDER'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED'

export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED'

export const DELETE_ORDER = 'DELETE_ORDER'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED'

export const FETCH_REVIEW = 'FETCH_REVIEW'
export const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS'
export const FETCH_REVIEW_FAILED = 'FETCH_REVIEW_FAILED'

export const FETCH_REVIEWS = 'FETCH_REVIEWS'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED'

export const ADD_REVIEW = 'ADD_REVIEW'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED'

export const DELETE_REVIEW = 'DELETE_REVIEW'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const BLOCK_USER = 'BLOCK_USER'
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const BLOCK_USER_FAILED = 'BLOCK_USER_FAILED'

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS'
export const ADD_TO_FAVORITE_FAILED = 'ADD_TO_FAVORITE_FAILED'

export const FETCH_FAVORITES = 'FETCH_FAVORITES'
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS'
export const FETCH_FAVORITES_FAILED = 'FETCH_FAVORITES_FAILED'